version: "3.3"

services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    env_file: .env
    volumes:
        - ./nginx/:/etc/nginx/
    ports:
      - "80:80"
      - "443:443"
      # TO DO:
      # В будущем возможно использование SSL сертификатов

  # БД Нужно ли ?

  # Сюда контейнер бэка

  # Сюда контейнер питона

  frontend:
    build: ./frontend
    restart: unless-stopped
    env_file: .env
