version: "3.3"

services:
  nginx:
    image: danday74/nginx-lua
    restart: unless-stopped
    env_file: .env
    volumes:
        - ./nginx:/nginx/conf
    ports:
      - "80:80"
      - "443:443"

  # БД

  # Бэк

  frontend:
    build: ./frontend
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
      - /frontend/dist